# Configuration for MongoDB
mongodb:
  host: localhost
  db: ehackathon

# Configuration for Database
postgres:  
  rdbms: postgres
  user: ehackathon
  pass: 12345
  ip: localhost
  port: 5432
  name: ehackathon
  sslmode: disable
  
# Configuration for ElasticSearch
elastic:
  host: localhost
  port: 9200
  name: ehackathon
  index: falabella
  type: products
 
# Server
server:
  port: 3000